dist: trusty

language: go

go:
  - 1.14

jobs:
  include:
    - stage: generate swager
      before_script:
      - go install github.com/go-swagger/go-swagger/cmd/swagger
      script:
      - swagger generate spec -o website/swaggerui/swagger.json
    - stage: install and use lint
      before_script:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint
      script:
      - golangci-lint run --skip-files swagger.go
      - go test ./pkg/... -race -coverprofile=coverage.txt -covermode=atomic
      - bash <(curl -s https://codecov.io/bash) # push results to CodeCov
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t go-simple-webapp .
      - docker images
      - docker tag go-simple-webapp $DOCKER_USERNAME/go-simple-webapp:1.${TRAVIS_BUILD_NUMBER}
      - docker push $DOCKER_USERNAME/go-simple-webapp:1.${TRAVIS_BUILD_NUMBER}

